# Host-controlled PSM profile: request one-hour TAU and zero-second Active-Time.
CONFIG_HOST_POWER_PROFILE_PSM=y
CONFIG_HOST_POWER_PROFILE_PSM_TAU="00100001"
CONFIG_HOST_POWER_PROFILE_PSM_ACTIVE_TIME="00000000"
